#!/usr/bin/env zsh

if [[ ${uname_txt} =~ ^Linux* ]]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

eval "$(starship init zsh)"
eval "$(rtx activate zsh)"
eval "$(sheldon source)"

###
# History設定
###
HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt share_history
setopt hist_ignore_dups
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt hist_reduce_blanks

###
# ENV
###
export LC_ALL=en_US.UTF-8
export LANG=ja_JP.UTF-8
export EDITOR=nvim

# export GOPATH=$(go env GOPATH)
export GO11MODULE=on

###
# alias
###
alias vi="nvim"
alias vim="nvim"
alias gs="git status"

alias relogin="exec $SHELL -l"

alias server="python -m SimpleHTTPServer "

# chezmoi
alias ce="chezmoi edit"
alias cad="chezmoi add"
alias cap="chezmoi apply"


# -----
## ghqとの連携。ghqの管理化にあるリポジトリを一覧表示する。ctrl - ]にバインド。
function peco-src () {
  local selected_dir=$(ghq list -p | peco --prompt="repositories >" --query "$LBUFFER")
  if [ -n "$selected_dir" ]; then
    BUFFER="cd ${selected_dir}"
    zle accept-line
  fi
  zle clear-screen
}
zle -N peco-src
bindkey '^]' peco-src
# -----

bindkey -v
